### PR TITLE
Add two more transformation examples

### PR DESCRIPTION
**Pull request by Boburmirzo**
Product Marketing requested two transformation code snippets for Weaviate and Debezium.

### CODE REVIEW

**Review by PabloPardoGarcia — COMMENTED** [review]
@Boburmirzo I'm not familiar with weaviate vector db yet, how the semantic search example relates to it?

Maybe it would be useful to add a docstring to the top, explaining in one or two lines what this does?

**Comment by Boburmirzo** [comment]
> @Boburmirzo I'm not familiar with weaviate vector db yet, how the semantic search example relates to it?
> 
> Maybe it would be useful to add a docstring to the top, explaining in one or two lines what this does?

Yes, it is a good idea. I will set a description of the method.

**Comment by Boburmirzo** [comment]
> > @Boburmirzo I'm not familiar with weaviate vector db yet, how the semantic search example relates to it?
> > Maybe it would be useful to add a docstring to the top, explaining in one or two lines what this does?
> 
> Yes, it is a good idea. I will set a description of the method.

@PabloPardoGarcia I added a description. Semantic search is one of the important function of all vector databases. The transformation part helps to optimize and enrich the input data for semantic searching.

**Comment by PabloPardoGarcia** [comment]
@Boburmirzo thanks!! 

Ok, so we enrich the incoming data with the category and it's the user's responsibility to save the output into the vector db.

**Comment by Boburmirzo** [comment]
> @Boburmirzo thanks!!
> 
> Ok, so we enrich the incoming data with the category and it's the user's responsibility to save the output into the vector db.

Yes, the idea of transformation prepares data to store them in DB in the consumer part at later stages. These transformation examples are not end-to-end. I also had idea of integrating Vector databases into the transformation as a built in storage, we will discuss this feature in person.

**Pull request merged**
